### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by darlingdaniel4790** [darlingdaniel4790/DigiGames1#1]
Time to design the frontend

**Comment by ghost** [comment]
Good day. I would like to contribute to this project. Can I get more information on how to do so?

**Comment by darlingdaniel4790** [comment]
> Good day. I would like to contribute to this project. Can I get more information on how to do so?

Hi Karen. 
This is just a dummy repo my friend and I are using to practice. There's really nothing to do here.
